### ISSUE TITLE
RuntimeException on 1.16.5 fabric

### ISSUE THREAD

**Issue by tim-db** [RuscalWorld/FabricExporter#2]
When trying to launch in on my 1.16.5 fabric minecraft server it instantly crashes and I receive the following error.
I have already changed from openjdk to Java 16, I hoped this would fix the mixin version 60 error but it didn't.
Are there any other requirements I'm not meeting?

`
[00:44:05] [main/INFO]: Loading for game Minecraft 1.16.5
[00:44:05] [ForkJoinPool-1-worker-15/WARN]: Non-Fabric mod JAR at "/home/tim/minecraft/carpet/mods/fabric-installer-0.7.4.jar", ignoring
[00:44:05] [main/WARN]: Warnings were found!
 - Mod 'FabricExporter' (fabricexporter) recommends any version of mod spark, which is missing!
         - You must install any version of spark.
[00:44:05] [main/INFO]: [FabricLoader] Loading 56 mods:
        - autoconfig1u@3.3.1
        - carpet@1.4.24
        - cloth-basic-math@0.5.1
        - cloth-config2@4.8.2
        - fabric@0.31.0+1.16
        - fabric-api-base@0.2.1+9354966b7d
        - fabric-biome-api-v1@3.1.1+ca58154a7d
        - fabric-blockrenderlayer-v1@1.1.5+ca58154a7d
        - fabric-command-api-v1@1.1.0+f9b3753b7d
        - fabric-commands-v0@0.2.2+ca58154a7d
        - fabric-containers-v0@0.1.11+9354966b7d
        - fabric-content-registries-v0@0.2.1+ca58154a7d
        - fabric-crash-report-info-v1@0.1.3+ca58154a7d
        - fabric-dimensions-v1@2.0.6+9354966b7d
        - fabric-entity-events-v1@1.0.3+ca58154a7d
        - fabric-events-interaction-v0@0.4.2+ca58154a7d
        - fabric-events-lifecycle-v0@0.2.1+ca58154a7d
        - fabric-game-rule-api-v1@1.0.6+ca58154a7d
        - fabric-item-api-v1@1.2.1+ca58154a7d
        - fabric-item-groups-v0@0.2.3+ca58154a7d
        - fabric-key-binding-api-v1@1.0.4+9354966b7d
        - fabric-keybindings-v0@0.2.1+ca58154a7d
        - fabric-lifecycle-events-v1@1.2.1+ca58154a7d
        - fabric-loot-tables-v1@1.0.2+ca58154a7d
        - fabric-mining-levels-v0@0.1.3+ca58154a7d
        - fabric-models-v0@0.2.1+ca58154a7d
        - fabric-networking-api-v1@1.0.1+ca58154a7d
        - fabric-networking-blockentity-v0@0.2.8+ca58154a7d
        - fabric-networking-v0@0.3.2+ca58154a7d
        - fabric-object-builder-api-v1@1.9.4+9354966b7d
        - fabric-object-builders-v0@0.7.2+ca58154a7d
        - fabric-particles-v1@0.2.4+ca58154a7d
        - fabric-registry-sync-v0@0.7.4+ca58154a7d
        - fabric-renderer-api-v1@0.4.1+ca58154a7d
        - fabric-renderer-indigo@0.4.4+ca58154a7d
        - fabric-renderer-registries-v1@2.2.1+ca58154a7d
        - fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d
        - fabric-rendering-fluids-v1@0.1.13+ca58154a7d
        - fabric-rendering-v0@1.1.2+ca58154a7d
        - fabric-rendering-v1@1.5.1+ca58154a7d
        - fabric-resource-loader-v0@0.4.2+ca58154a7d
        - fabric-screen-api-v1@1.0.0+c045166c7d
        - fabric-screen-handler-api-v1@1.1.5+9354966b7d
        - fabric-structure-api-v1@1.1.4+ca58154a7d
        - fabric-tag-extensions-v0@1.1.1+ca58154a7d
        - fabric-textures-v0@1.0.6+ca58154a7d
        - fabric-tool-attribute-api-v1@1.2.6+ca58154a7d
        - fabricexporter@1.0.3
        - fabricloader@0.11.6
        - java@16
        - krypton@0.1.2
        - lithium@0.6.4
        - malilib@0.10.0-dev.21+arne.2
        - minecraft@1.16.5
        - phosphor@0.7.1+build.11
        - shulkerboxtooltip@2.3.5+1.16.5
 
[00:44:05] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/tim/minecraft/carpet/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[00:44:05] [main/INFO]: Loaded configuration file for Lithium: 80 options available, 1 override(s) found
[00:44:06] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[00:44:06] [main/WARN]: Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[00:44:06] [main/ERROR]: fabricexporter.mixins.json:ServerHandshakeNetworkHandlerMixin: Unsupported mixin class version 60. Mixin requires compatibility level JAVA_17 or above.
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unsupported mixin class version 60. Mixin requires compatibility level JAVA_17 or above.
        at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validateClassVersion(MixinInfo.java:363) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:333) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:904) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:674) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) [fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) [?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:232) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]

[00:44:12] [main/INFO]: Compression will use libdeflate (Linux x86_64), encryption will use OpenSSL 1.1.x (Linux x86_64)
[00:44:12] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabricexporter'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: me/lucko/spark/api/statistic/StatisticWindow$TicksPerSecond
        at ru.ruscalworld.fabricexporter.MetricRegistry.registerDefault(MetricRegistry.java:37) ~[fabricexporter-1.0.3.jar:?]
        at ru.ruscalworld.fabricexporter.FabricExporter.onInitialize(FabricExporter.java:33) ~[fabricexporter-1.0.3.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: me.lucko.spark.api.statistic.StatisticWindow$TicksPerSecond
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at ru.ruscalworld.fabricexporter.MetricRegistry.registerDefault(MetricRegistry.java:37) ~[fabricexporter-1.0.3.jar:?]
        at ru.ruscalworld.fabricexporter.FabricExporter.onInitialize(FabricExporter.java:33) ~[fabricexporter-1.0.3.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more
`

**Comment by tim-db** [comment]
Fixed this by installing the [Spark mod](https://www.curseforge.com/minecraft/mc-mods/spark), it wasn't clear to me that this was necessary.

**Comment by tim-db** [comment]
Java version 16 is unsupported by forge and many other mods and does not work on such servers.

Would it be possible to compile this in Java 8, since this is the most common Java version for minecraft?

**Comment by tim-db** [comment]
It seems that the only important difference between version 1.0.1 and 1.0.3 of your release is the Java version used to compile. So by using version 1.0.1 I got this to work on my instance.
