### ISSUE TITLE
Support for 1.18.1?

### ISSUE THREAD

**Issue by deejaypro** [RuscalWorld/FabricExporter#4]
Hey,
are you planning on releasing a Version for MC 1.18.1?

**Comment by RuscalWorld** [comment]
Support for 1.18.1 should not require any changes in codebase. Do you experience any issues while using this with 1.18.1?

**Comment by deejaypro** [comment]
Just tried it an ran into an error:

```
[21:25:41] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabricexporter'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.12.jar:?]
        at net.minecraft.server.Main.main(Main.java:106) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [server.jar:0.10.2]
Caused by: java.lang.NoClassDefFoundError: me/lucko/spark/api/statistic/StatisticWindow$TicksPerSecond
        at ru.ruscalworld.fabricexporter.MetricRegistry.registerDefault(MetricRegistry.java:37) ~[fabricexporter-1.0.3.jar:?]
        at ru.ruscalworld.fabricexporter.FabricExporter.onInitialize(FabricExporter.java:33) ~[fabricexporter-1.0.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
        ... 16 more
Caused by: java.lang.ClassNotFoundException: me.lucko.spark.api.statistic.StatisticWindow$TicksPerSecond
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at ru.ruscalworld.fabricexporter.MetricRegistry.registerDefault(MetricRegistry.java:37) ~[fabricexporter-1.0.3.jar:?]
        at ru.ruscalworld.fabricexporter.FabricExporter.onInitialize(FabricExporter.java:33) ~[fabricexporter-1.0.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
        ... 16 more
```

**Comment by RuscalWorld** [comment]
Just set `use-spark` to `false` in `exporter.properties` or install Spark mod. This is not related with version of Minecraft.

**Comment by deejaypro** [comment]
Whoops. I feel stupid now. It works now. Sorry :D
